# Generated by Django 4.0.4 on 2022-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=81, verbose_name='Title')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.TextField(max_length=180)),
                ('full_description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
