# Generated by Django 4.0.4 on 2022-05-19 12:32

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_image_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=froala_editor.fields.FroalaField(max_length=180),
        ),
    ]
