# Generated by Django 4.0.4 on 2022-05-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_full_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
    ]
