# Generated by Django 4.0.4 on 2022-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Title'),
        ),
    ]
